# Generated by Django 4.2.7 on 2023-11-29 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ususarios',
            new_name='Usuarios',
        ),
    ]
