# Generated by Django 4.2.7 on 2023-11-30 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_rename_ususarios_usuarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
    ]
